$(document).ready(function() {
   $('.messp').click(function(){
       $('#mesmess').toggle('hide');
       $('#forum').toggle('hide');
       $('#messform').toggle('hide');
            });
   $('.messgs').click(function(){
       $('#mp').toggle('hide');
       $('#forum').toggle('hide');
       $('#messform').toggle('hide');
            });
    $('.grpchat').click(function(){
        $('#mp').toggle('hide');
        $('#mesmess').toggle('hide');
        $('#messform').toggle('hide');
            });
    $('.formcont').click(function(){
        $('#mp').toggle('hide');
        $('#mesmess').toggle('hide');
        $('#forum').toggle('hide');
            }); 
    })